"""
Bug-fix agent endpoints.
"""

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.schemas.task import BugFixRequest, TaskResponse
from app.services.repository_service import RepositoryService
from app.workers.tasks import bug_fix_task

router = APIRouter()


@router.post("/fix", response_model=TaskResponse, status_code=202)
async def submit_bug_fix(
    request: BugFixRequest,
    db: Session = Depends(get_db),
):
    """
    Submit a bug fix request.
    
    The autonomous agent will:
    1. Analyze the issue description
    2. Retrieve relevant files and functions
    3. Generate a repair plan
    4. Create and apply patches
    5. Run tests in sandbox
    6. Iterate if tests fail (max 2 retries)
    7. Return final report with diff and confidence score
    
    Example issues:
    - "Login returns 500 error when password contains special characters"
    - "Payment retry logic doesn't respect max_retries configuration"
    - "Memory leak in connection pool cleanup"
    """
    service = RepositoryService(db)
    repo = service.get_repository(request.repository_id)
    
    if not repo:
        raise HTTPException(status_code=404, detail="Repository not found")
    
    if repo.status.value != "ready":
        raise HTTPException(
            status_code=400,
            detail=f"Repository not ready. Current status: {repo.status.value}"
        )
    
    # Create task record
    from app.models.task import Task, TaskType
    task = Task(
        repository_id=request.repository_id,
        task_type=TaskType.BUG_FIX,
        query=request.issue_description,
        test_command=request.test_command,
        status="pending"
    )
    db.add(task)
    db.commit()
    db.refresh(task)
    
    # Queue bug fix task
    bug_fix_task.delay(task.id, request.issue_description, request.test_command)
    
    return task


@router.get("/{task_id}")
async def get_task_status(
    task_id: int,
    db: Session = Depends(get_db),
):
    """Get status and results of a bug fix task."""
    from app.models.task import Task
    
    task = db.query(Task).filter(Task.id == task_id).first()
    
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")
    
    return {
        "id": task.id,
        "type": task.task_type.value,
        "status": task.status.value,
        "query": task.query,
        "result": task.result,
        "error_message": task.error_message,
        "confidence_score": task.confidence_score,
        "latency_ms": task.latency_ms,
        "created_at": task.created_at,
        "completed_at": task.completed_at
    }


@router.get("/{task_id}/diff")
async def get_task_diff(
    task_id: int,
    db: Session = Depends(get_db),
):
    """Get the patch diff generated by a bug fix task."""
    from app.models.task import Task
    
    task = db.query(Task).filter(Task.id == task_id).first()
    
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")
    
    if task.status.value != "completed":
        raise HTTPException(
            status_code=400,
            detail=f"Task not completed. Status: {task.status.value}"
        )
    
    result = task.result or {}
    
    return {
        "task_id": task_id,
        "patch": result.get("patch"),
        "changed_files": result.get("changed_files"),
        "test_output": result.get("test_output")
    }
